language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-compose
    branch: publish
  api_key:
    secure: sFHv7ZM5h18gzcTq+YYPrkIuFEJiSGSY2QsArGlAay2KQqqaAGLeXTSdm8JxCgrqNYbKRY4tmil6YPEoT50umaAIEEpgWFFb9g7P7b09oEa0Lr/Ia3HjW162UjwWgndT9JKRHJc3NZ6QEWvW21CxY3vUNU/2lsJawQptJdLiHNvyCz0D7vWiL860yrr0eIaRqf78nPqflK6NkCj99YqQ1xrkdCuvS8TiGn26IM2zYFVW6ZaTE0XEdeNGsd66atwrjMC351qSs+HXZK+EgZPGLzlr1aSofQw7DEbPBruYAKjApz3JwyApKPh7BSvNa7/mC6HJ/QtK0n/zB7009DRIOKCp+5E0xT+bbvwPGOW+iVGTtAxbaXvhcCq05h7YMzjxAxARwUFhclTGM9yuH0KDtupJ0C4h+J5MKX9rmg4JCAcTmPzsv9RdznGdqbPZcyAZLERUQo6tWd8KXGIcGZB1f7dLhvrBUK7WR4Q+oRv8C9HI7U2m0ig9tKDn5T8fJVKSNg6pFA1W3+OZ3qRFU7dVILsAICkHiGOHUA1JuD0th3zEhgIAxnf3e7etCq+yvuY6RdOkziP3ulK3tQQr8Fg+I+iKnNTWydhLYdRbha9w90jrcS4IpHdvPmk68zXIh5+jC69uEntPkr6dtD75sNSUQ6Pgqz0nZzn+eGt2TCiJ/mQ=
