language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-compose
    branch: publish
  api_key:
    secure: x75IwmK7ZG6piU4p8w+9y5Eou40m6mruwpDVkdK5XA4MYCGA7A3JxIRo+b+dCCr08cvdUo4SqimQEYN12hAdk3L4BUt8qLopT1uYEfC8cnjAGlgrbiar6L1U18++bQ/kFxuB/QSuBcysU8v8gcbumynM0UjWLDbRBVzVbHtge9hMjpYkxi3i3fC1PU7dwWVk2fyl+J5doccqPWIca4Er7R5mrtt+WZuQhY0gUiv0aUSv8X22F91fB/gta3sUSiPIX/a66tK/D59HBm3A0DFlhuXJlx3lTlDcO+FkeuDG3CG+Xy+6WbQRBPREFTfEjrxnQ352jVqrpIkDFdZuHgVur4rSXBzATS0C2p7kWGWld1G2Q9MWZdVYKZKRSHuVJOrHa5HG4QWR4dAbcrLHpwH+OeHcLP3buLsBtSDmQkGBNDiZNhwCxDajMchgAkPz/hLBKrj2g33vKyELynoQnhtWj0k4zI0VfTbH14FxeePi0l5Ca3p8lmpLFe0jdudwMtphL9a4lxzvtrzP/mm8CAxw7nDCppPEj2l+uUeXYRlIwyOSK5yGKxnwWiOFM931WLrbW9LK8iqwa/9k65gitHP7FCBdUhX+XYfT5kdtkiaZhZx4QMQpqw6w1d52PDhVwnvCkoTH4Dp6/62XdeTS0ttM62MRwh74wGRUAMG+JzG0r5Q=
